### ISSUE TITLE
Failed to decode config file

### ISSUE THREAD

**Issue by phit** [belst/discord-irc-birdge#9]
Not sure if I'm completely blind, I'm trying to setup your bridge right now and getting nowhere, running discord-irc-bridge-0.1.0 from the release section.

Here's my config http://vpaste.net/ATbX5
Startup log http://vpaste.net/P9pU3
Ran it through a json parser and it's definitely valid, would be really thankful if you could tell me what's wrong.

**Comment by belst** [comment]
Yeah I knew about those typos for a while. But thanks for reminding me to update the github version

**Comment by phit** [comment]
No problem, thanks for the quick fix! Not sure if it's intentional but the project title also has a typo "birdge".
